### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by mindstormer12** [spantaleev/redshift-scheduler#3]
redshift-scheduler is a fork of redshift, right? Last commit was around December 2014, but the latest version of redshift was released around January 2015.

**Comment by spantaleev** [comment]
It's not a fork of redshift. It's a separate program, which controls redshift.

You need redshift installed to be able to make use of this. Whether it still works with the version from January 2015, I can't say (I haven't tested). Feel free to test and let me know.
