### ISSUE TITLE
redshift-scheduler and redshift show different temperatures

### ISSUE THREAD

**Issue by marfit** [spantaleev/redshift-scheduler#6]
I'm using the [info-redshift-temp ](https://github.chttps://education.githuhttps://education.githuhttps://education.github.com/discount_requestsb.com/discount_requestsb.com/discount_requestsom/polybar/polybar-scripts/tree/master/polybar-scripts/info-redshift-temp) script for polybar, which essentially uses the `redshift -p` command to get the current temperature.

The temperatures shown by this script are not the same as the temperatures shown by the debug-mode `redshift-scheduler -d` . The temps I'm getting form `redshift -p` are always higher and mostly stuck at a fixed value (e.g. 4500k) for half an hour even though redshift-scheduler seams to work correctly. 

**First question:** Why does redshift print a different (wrong) temperature?

**Second question:** Is there an easy way to print the current temperature with redshift-scheduler so it can be used in a polybar-modul?

\
Thanks for considering and the great work so far!

**Comment by spantaleev** [comment]
From what I see `redshift -p` contacts some geolocation APIs. The temperature reported by it is likely what `redshift` itself considers sensible for the current time. My tests show that it's not the actual currently set temperature.

You can test it yourself by:
- stopping `redshift-scheduler` so it won't interfere
- running `redshift -p` and observing the value
- using `redshift -O SOME_OTHER_VALUE` to set another value
- observe that the screen redness changed (that your value was applied)
- run `redshift -p` again and see what it reports -- it's likely the same value as before and not `SOME_OTHER_VALUE`

I guess it may be possible to make `redshift-scheduler` print the current temperature.. or there might be some other way to ask `redshift` to print it, although I haven't found one yet.

**Comment by spantaleev** [comment]
I've added a `-p` flag to `redshift-scheduler`, which makes it print the temperature calculated according to the current rules. It's not necessarily the same as the temperature applied by `redshift`, especially if `redshift-scheduler` is not running.. but it's probably useful for your use case.

Version `1.3.0` of `redshift-scheduler` contains support for the `-p` flag.
